In [1]:
import torch
B = 4           # batch size
n_species = 6   # numero specie
n_genus = 3     # numero generi
embed_dim = 5

X = torch.randn(B, embed_dim)
print(X)
species_proxies = torch.randn(n_species, embed_dim)
print(species_proxies)
genus_proxies = torch.randn(n_genus, embed_dim)
print(genus_proxies)

tensor([[ 1.1630, -0.1556,  2.4210, -1.1831, -1.2614],
        [-0.7722, -0.4927,  0.2562, -0.9164,  1.2938],
        [ 0.6793,  1.4275,  0.1416,  1.6654,  1.0798],
        [ 0.3880, -0.0432, -1.1535, -0.6715,  2.0107]])
tensor([[-0.1966,  0.8050, -2.5530, -1.3111,  0.2671],
        [-0.9903,  0.6585, -0.0440, -0.1695,  0.7622],
        [ 0.4498,  0.5775, -0.4006, -1.3843,  0.1816],
        [-0.7435, -0.0347, -0.8803,  0.6105,  1.3529],
        [ 0.8438, -1.1485,  2.9973,  0.1097, -2.6894],
        [ 0.2802, -1.6968,  0.7423,  1.9205, -0.2709]])
tensor([[ 0.2908, -0.5686,  0.7238, -1.1722,  0.9676],
        [ 0.9029,  0.5301, -0.5790, -0.3187, -0.0518],
        [ 2.0562,  0.2680, -0.3042, -1.1506, -0.4365]])


In [2]:
import src.poincare_math as pmath

dist_genus= pmath.dist_matrix(species_proxies, genus_proxies, 0.01)
print(dist_genus)

tensor([[ 7.6089,  5.2296,  7.0049],
        [ 4.4559,  4.3201,  7.0396],
        [ 3.7030,  2.4360,  3.6717],
        [ 5.5058,  4.9575,  7.8114],
        [ 9.8591, 10.1871, 10.0343],
        [ 7.2659,  7.1441,  8.6978]])


In [41]:
# Da qui


T_species = torch.randint(0, 150, (8,))
T_species

tensor([  8, 147,  48, 117, 141, 135, 122, 142])

In [44]:
species_proxies = torch.randn(150, embed_dim)

In [45]:
genus_proxies = torch.randn(150, embed_dim)

In [49]:
unique_species, inv_idx = torch.unique(T_species, return_inverse=True)
unique_species

tensor([  8,  48, 117, 122, 135, 141, 142, 147])

In [50]:
species_proxies_unique = species_proxies[unique_species]
species_proxies_unique

tensor([[-0.0820, -1.9972,  0.7281, -0.0689,  0.1974],
        [ 0.1255, -0.2164, -0.6359,  0.9720, -1.8192],
        [-1.6939,  0.3302, -0.2294,  0.0596,  0.0245],
        [ 1.1913,  0.1414,  0.4699, -1.3894, -0.5600],
        [-0.9565,  0.7391, -0.7637,  0.4572,  0.6229],
        [-0.2579, -0.9814,  0.3811, -2.3947, -0.0765],
        [-1.1352,  0.3178,  0.0544,  0.6429,  0.1789],
        [-1.4009,  1.8252,  0.1493, -0.2660, -1.0913]])

In [54]:
dist_genus= pmath.dist_matrix(species_proxies_unique, genus_proxies, 0.01)
dist_genus.shape

torch.Size([8, 150])

In [40]:
T_genus = torch.randint(0, 13, (8,))
print(T_genus)

tensor([ 5,  9,  3,  3,  4, 11,  7,  1])


In [55]:
import pandas as pd
df = pd.read_csv("labeled_seen_gallery.csv", sep="\t")
species_to_genus = dict(zip(df["Species_ID"], df["Genus_ID"]))
genus_targets = torch.tensor([species_to_genus[s.item()] for s in unique_species])
print(genus_targets)

tensor([ 9, 34,  9, 44,  0, 12, 18,  1])


In [57]:
P_one_hot_genus = torch.nn.functional.one_hot(genus_targets, num_classes=60).float()
print(P_one_hot_genus)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       

In [8]:
N_one_hot_genus = 1 - P_one_hot_genus
N_one_hot_genus

tensor([[1., 1., 0.],
        [0., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])

In [59]:
valid_genus_proxies_mask=(P_one_hot_genus.sum(dim=0) != 0).float()
valid_genus_proxies_mask

num_valid_genus_proxies = valid_genus_proxies_mask.sum().clamp(min=1.0)
print(num_valid_genus_proxies)

tensor(7.)


In [15]:
torch.nn.functional.softplus(dist_genus)* P_one_hot_genus

RuntimeError: The size of tensor a (6) must match the size of tensor b (4) at non-singleton dimension 0

In [17]:
P_one_hot_genus

tensor([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

In [11]:
pos_genus_term=torch.sum(torch.nn.functional.softplus(dist_genus) * P_one_hot_genus) / num_valid_genus_proxies

RuntimeError: The size of tensor a (6) must match the size of tensor b (4) at non-singleton dimension 0

In [22]:
import pandas as pd
df=pd.read_csv("labeled_seen_gallery.csv",sep="\t")
df

Sample                     Species HQ  Species_ID  \
0        SAMN10221109            Escherichia coli  T           0   
1        SAMEA3507073      Neisseria meningitidis  T           1   
2        SAMN31671018         Salmonella enterica  T           2   
3        SAMN02570323     Acinetobacter baumannii  T           3   
4        SAMN30543411  Mycobacterium tuberculosis  T           4   
...               ...                         ... ..         ...   
1438397  SAMN08607286         Salmonella enterica  T           2   
1438398  SAMEA3171026    Streptococcus pneumoniae  T          10   
1438399  SAMN10895949         Salmonella enterica  T           2   
1438400  SAMN17138828         Salmonella enterica  T           2   
1438401  SAMN31662491            Escherichia coli  T           0   

                 Genus  Genus_ID  
0          Escherichia        28  
1            Neisseria        31  
2           Salmonella         3  
3        Acinetobacter        18  
4        Mycobacterium        29  
...                ...       ...  
1438397     Salmonella         3  
1438398  Streptococcus        43  
1438399     Salmonella         3  
1438400     Salmonella         3  
1438401    Escherichia        28  

[1438402 rows x 6 columns]

In [25]:
species_to_genus=dict(zip(df["Species_ID"],df["Genus_ID"]))
len(species_to_genus)

154